[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "24"

# Redirects for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Bundle issues where it exceeds 250MB
# My code is not for Server anyway
[functions]
    included_files = []

[functions."___netlify-server-handler"]
    excluded_patterns = [
        "node_modules/kokoro-js/**",
        "node_modules/onnxruntime-web/**",
        "node_modules/@huggingface/transformers/**",
    ]
